version: '3.7'

services:
  postgres:
    image: 'postgres'
    container_name: 'pg'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: workalu
      POSTGRES_USER: workalu
      POSTGRES_PASSWORD: workalu
